# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v1
      
    #Install packages
    #- name: Install packages
    #  run: npm install --save katalon-studio/katalon-agent#v1.4.0

    # Runs Katalon Studio Action
    - name: Katalon Studio Github Action
      uses: atluu315/Katalon_Studio_Github_Action@1.0
      with:
          version: '7.5.5'
          projectPath: '${{ github.workspace }}\simple_project_2.prj'
          args: '-noSplash -retry=0 -testSuiteCollectionPath="Test Suites/New Test Suite Collection" -apiKey= ${{ secrets.API_KEY }} --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY'
